# This is a basic workflow to help you get started with Actions

name: CI

on:
  push
  
jobs:
  build:
    runs-on: ubuntu-latest
    container: Dockefile
    steps:

      - name: Checkout
        uses: actions/checkout@v2
      - name: check latex
        uses: ./
